### ISSUE TITLE
毎朝6時をまたぐ試合がエラーとなる

### ISSUE THREAD

**Issue by smly** [Apricot-S/majsoulrpa#127]
毎朝6時にはクエスト更新やショップの更新などの通知メッセージがあります。そのため試合が6時をまたがって行われた場合、以下のメッセージを受け取ります。

* `('inbound', '.lq.NotifyActivityTaskUpdate',  {'progresses': ...})`
* `('outbound', '.lq.Lobby.fetchShopInterval', ...)`

MatchPresentation では対応できていないためエラーとなります。
`_on_end_of_match()` などのメッセージを dequeue する処理において、上述したメッセージを dequeue してもエラーが発生しないよう修正する必要があります。

**Comment by Apricot-S** [comment]
現在`HomePresentation`にある`_discard_messages_across_dates`のような処理を挟めばよいですが
対局中は無駄な処理で操作が遅れるのも問題であるため調整が必要かもしれません。

また、6時をまたいだ際のメッセージは基本的に読み捨ててよいですが、`payMonthTicket`だけは開運御守の演出があるか検出するために必要となります。
対局中でも`payMonthTicket`がやりとりされるのか、それともホーム画面に戻ってからやりとりされるかをまず調査する必要があります。
対局中にもやりとりされる場合、`HomePresentation`では`payMonthTicket`の有無に関係なく開運御守を検知する処理が必要かもしれません。

**Comment by Apricot-S** [comment]
9c9c1c475ea4b0949956c30f0ffbb9185db386ac にて対応後、6時をまたいでもエラーとならないことを確認しました。
私の環境で6時をまたいだ際にやり取りされたメッセージを以下に記載します。
logに表示された順に記載します。

```text
...
('inbound', '.lq.NotifyDailyTaskUpdate', {'progresses': ...
('inbound', '.lq.NotifyShopUpdate', {'shop_info': ...
('inbound', '.lq.NotifyAccountChallengeTaskUpdate', {'level': ...
('inbound', '.lq.NotifyAccountUpdate', {'update': ...
...
('outbound', '.lq.Lobby.fetchShopInterval', {}, ...
('outbound', '.lq.Lobby.fetchActivityInterval', {}, ...
...
('outbound', '.lq.Lobby.fetchShopInterval', {}, ... (注: 2回目のやり取りがされている)
('outbound', '.lq.Lobby.fetchActivityInterval', {}, ... (注: 2回目のやり取りがされている)
...
```

上記logでは`.lq.NotifyActivityTaskUpdate`はありませんでしたが、`MatchPresentation`で読み捨てるメッセージとしては追加しています。
開運御守があるかどうかやイベント期間中かどうかでメッセージの種類が変わると予想されるため、現時点での完全な対応は難しいかもしれません。

**Comment by smly** [comment]
@Apricot-S 差分を拝見しまいた。問題なさそうです。ご対応ありがとうございます！
