### ISSUE TITLE
詳細な導入ドキュメントまたはインストール手順を送っていただけますか? please&thank u

### ISSUE THREAD

**Issue by lin-strive** [Apricot-S/majsoulrpa#185]
please&thank u
詳細な導入ドキュメントまたはインストール手順を送っていただけますか?

**Comment by Apricot-S** [comment]
ご覧いただきありがとうございます。

> 詳細な導入ドキュメント
- どのようなものを想定していますか?

> インストール手順
- `pip install git+https://github.com/Apricot-S/majsoulrpa.git` でインストールしてください。`poetry add` などでも構いません。
- `examples` を参考にご自身の bot アプリケーションを作成してください。

よろしくお願いします。

**Comment by lin-strive** [comment]
ありがとう！ デプロイしてみます ご回答ありがとうございます 私は Java エンジニアなので、手動でのデプロイや開発方法についてはあまり詳しくないかもしれません。xd

**Comment by Apricot-S** [comment]
追加の質問がないためクローズします。
