### ISSUE TITLE
`user_data_dir` in the `config.toml` saved the data at wrong location on Windows

### ISSUE THREAD

**Issue by shinkuan** [Apricot-S/majsoulrpa#277]
Tested on Windows 11, Python 3.11.

When `user_data_dir` is set to a value in the `config.toml`, the data is saved at wrong location.

Example of `config.toml`: 
```
[browser]
user_data_dir = "./user_data"                # User data directory (comment out this line to use incognito mode).
```

**Expected:**
A dir called user_data appear at the execute location and the data is in there.

**What Happened:**
A dir called user_data appear at the execute location but data is not saved there.
Instead, it saved "./user_data" to `<location of playwright installed>/user_data`

**Comment by Apricot-S** [comment]
Thank you for reporting the issue.
I was able to reproduce the bug on my side as well.
I checked and found that the patch you provided does not work as expected when a relative path is set to `user_data_dir` using `pathlib.Path`.

Example:

```python
# examples/moqie.py
# Line 31
    with RPA(user_data_dir=Path("./user_data")) as rpa:
```

A revised proposal is currently being prepared.

**Comment by shinkuan** [comment]
Hello, thanks for the response.

Can you check https://github.com/Apricot-S/majsoulrpa/pull/278/commits/bf41e7299a61e06629b71655ee0315c8eb40b2e6 and see if that fixes the problem when a relative path is set to `user_data_dir` using `pathlib.Path`?

**Comment by Apricot-S** [comment]
Thank you for your immediate response.
It worked correctly.

There are some things to fix, so please respond to the reviews.
